image: node:8
  
variables:               
# ----------------------------------------------------------------------------------    
# It is important you register @ harbormaster.ai in order to obtain an API token.  
# Once you have this token, assign it to an environment variable named 
#
# HARBORMASTER_API_TOKEN
#
# Learn more about assign environment variables at:
#
# https://docs.gitlab.com/ee/ci/variables/README.html#add-a-cicd-variable-to-an-instance
# ----------------------------------------------------------------------------------

# ----------------------------------------------------------------------------------
# project generation YAML file containing the generation directives 
# ----------------------------------------------------------------------------------
    PROJECT_YAML_FILE: "samples/project-as-code/django-project-as-code.yml" 

stages:
  - generate

before_script:
    - echo "installing Harbormaster Command Line Interface..."
    - npm install -g harbormaster_ai
    - echo "initializing Harbormaster CLI with provided api-token..."
    - harbormaster_ai init $HARBORMASTER_API_TOKEN

build:
  stage: generate
  script: 
    - echo "generating project files..."
    - harbormaster_ai project_generate ${CI_PROJECT_DIR}/$PROJECT_YAML_FILE -q true
