image: node:8
  
variables:
# use this api-token or register for your own at www.realmethods.com
    API_TOKEN: "CBc10800RKddRGQh"                
   
# each of the following paths are relative to the root of this repository
# each file is used as an example for you to review and modify as needed

# project generation directives : 
    PROJECT_YAML_FILE: "samples/project-as-code/django-project-as-code.yml" 
      
stages:
  - generate

before_script:
    - echo "installing Harbormaster Command Line Interface..."
    - npm install -g harbormaster_ai
    - echo "initializing Harbormaster CLI with provided api-token..."
    - harbormaster_ai init $API_TOKEN

build:
  stage: generate
  script: 
    - echo "generating project files..."
    - harbormaster_ai project_generate ${CI_PROJECT_DIR}/$PROJECT_YAML_FILE -q true
